import { Commodity, TipoPrezzo } from '@prisma/client';
import type { Prisma } from '@prisma/client';

export const OFFERTE_SEED: Prisma.OffertaCreateManyInput[] = [
  {
    nome: 'Enel Fix Business Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.FISSO,
    potenzaMinKw: 0,
    potenzaMaxKw: 15,
    prezzoFisso: 0.173,
    ccvMensile: 12,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: false,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Business Super Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.FISSO,
    potenzaMinKw: 3,
    potenzaMaxKw: 25,
    prezzoFisso: 0.15899,
    ccvMensile: 16,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Fix Business Start Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.FISSO,
    potenzaMinKw: 0,
    potenzaMaxKw: 25,
    prezzoFisso: 0.18706,
    ccvMensile: 16,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Business WOW Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.FISSO,
    potenzaMinKw: 3,
    potenzaMaxKw: 25,
    prezzoFisso: 0.198,
    ccvMensile: 13,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Flex Control Business Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.VARIABILE_CAP,
    potenzaMinKw: 0,
    potenzaMaxKw: 15,
    parametroAlfa: 0.029,
    cap: 0.163,
    ccvMensile: 17,
    durataMesi: 12,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'DUAL / MULTI'
  },
  {
    nome: 'Enel Flex Control Impresa Luce',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.VARIABILE_CAP,
    potenzaMinKw: 15,
    potenzaMaxKw: 25,
    parametroAlfa: 0.033,
    cap: 0.169,
    ccvMensile: 30,
    durataMesi: 12,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Business Oro Happy 12-13',
    commodity: Commodity.LUCE,
    tipoPrezzo: TipoPrezzo.PERSONALIZZATA,
    potenzaMinKw: 3,
    potenzaMaxKw: 25,
    prezzoFisso: 0.173,
    ccvMensile: 16,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: false,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI',
    strutturaPrezzo: 'Personalizzata',
    scontoPercento: 0.0905,
    oreInizioAgevolazione: 12,
    oreFineAgevolazione: 15,
    note: 'Sconto dal 2° anno pari a 0,0905 sulla fascia oraria 12-15'
  },
  {
    nome: 'Enel Fix Business Gas',
    commodity: Commodity.GAS,
    tipoPrezzo: TipoPrezzo.FISSO,
    prezzoFisso: 0.74,
    ccvMensile: 15,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: false,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Fix Business Start Gas',
    commodity: Commodity.GAS,
    tipoPrezzo: TipoPrezzo.FISSO,
    prezzoFisso: 0.74,
    ccvMensile: 15,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI'
  },
  {
    nome: 'Enel Flex Control Business Gas',
    commodity: Commodity.GAS,
    tipoPrezzo: TipoPrezzo.VARIABILE_CAP,
    parametroAlfa: 0.17,
    cap: 0.8579,
    ccvMensile: 20,
    durataMesi: 12,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL / MULTI',
    note: 'CAP da riverificare con la rete commerciale'
  },
  {
    nome: 'Enel Business WOW Gas',
    commodity: Commodity.GAS,
    tipoPrezzo: TipoPrezzo.FISSO,
    prezzoFisso: 0.74,
    ccvMensile: 15,
    durataMesi: 24,
    disponibileTablet: true,
    disponibileCartaceo: true,
    canalePreferenziale: 'Tablet',
    vendibilita: 'SINGLE / DUAL'
  }
];

export const PARAMETRI_SEED: Prisma.ParametroDettaglioCreateManyInput[] = [
  { chiave: 'ACCISA_LUCE_KWH', etichetta: 'Accisa energia elettrica', categoria: 'Accise e IVA', commodity: Commodity.LUCE, valore: 10.27, unita: '€/fattura', ordinamento: 1 },
  { chiave: 'IVA_PERC_LUCE', etichetta: 'IVA', categoria: 'Accise e IVA', commodity: Commodity.LUCE, valore: 10, unita: '%', ordinamento: 2 },
  { chiave: 'TRASMISSIONE_LUCE', etichetta: 'Trasmissione', categoria: 'Trasmissione e oneri', commodity: Commodity.LUCE, valore: 9.78, unita: '€/fattura', ordinamento: 3 },
  { chiave: 'QUOTA_FISSA_LUCE', etichetta: 'Quota fissa (oneri di rete)', categoria: 'Trasmissione e oneri', commodity: Commodity.LUCE, valore: 6.37, unita: '€/fattura', ordinamento: 4 },
  { chiave: 'QUOTA_POTENZA_LUCE', etichetta: 'Quota potenza', categoria: 'Trasmissione e oneri', commodity: Commodity.LUCE, valore: 24.87, unita: '€/fattura', ordinamento: 5 },
  { chiave: 'ALTRE_VOCI_LUCE', etichetta: 'Altre voci', categoria: 'Altre voci', commodity: Commodity.LUCE, valore: 0, unita: '€/fattura', ordinamento: 6 },
  { chiave: 'ACCISA_GAS_SMC', etichetta: 'Accisa gas', categoria: 'Accise e IVA', commodity: Commodity.GAS, valore: 0, unita: '€/Smc', ordinamento: 1 },
  { chiave: 'IVA_PERC_GAS', etichetta: 'IVA', categoria: 'Accise e IVA', commodity: Commodity.GAS, valore: 22, unita: '%', ordinamento: 2 }
];
